{
 "title": "Technical Support Statistics Dashboard",
 "description": "This is a modification of https://grafana.com/grafana/dashboards/10840 by leandro4gl.  Thanks for your initial dashboard. It was very helpful to create this one.",
 "tags": [
  "ticket",
  "osticket",
  "SLA",
  "backlog",
  "open",
  "closed"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<h1 style=\"text-align: center;\">ESG Technical Support Statistics</h1>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 2 },
   "content": "<h2 style=\"text-align: center;\">Today</h2>\n<hr>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 2 },
   "content": "<h2 style=\"text-align: center;\">Yesterday</h2>\n<hr>"
  },
  {
   "title": "On-Time Resolution",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 2 },
   "targets": [
    {
     "rawSql": "select (sum(case when t.created + interval s.grace_period hour <= now() then 0 else 1 end) / count(*)) * 100 pct_sla_on_time\r\n  from ost_ticket t\r\n  left join ost_sla s\r\n    on s.id = t.sla_id\r\n where closed is null\r\n"
    }
   ]
  },
  {
   "title": "Open by Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 2 },
   "targets": [
    {
     "rawSql": "select ts.name Status\r\n     , count(*) Qty\r\n  from ost_ticket t\r\n  left join ost_ticket_status ts\r\n    on ts.id = t.status_id\r\n where ts.state = 'open' and t.dept_id = 1\r\n group by 1\r\n order by 2 desc, 1\r\n"
    }
   ]
  },
  {
   "title": "Open By Age",
   "type": "table",
   "description": "Number of tickets open for this time by age",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 2 },
   "targets": [
    {
     "rawSql": "select case \r\n            when TIMESTAMPDIFF(HOUR,t.created,ifnull(t.closed,now())) <= 02 then '0. Up to 2 Hours'\r\n            when TIMESTAMPDIFF(HOUR,t.created,ifnull(t.closed,now())) <= 04 then '1. Up to 4 Hours'\r\n            when TIMESTAMPDIFF(HOUR,t.created,ifnull(t.closed,now())) <= 08 then '2. Up to 8 Hours'\r\n            when TIMESTAMPDIFF(HOUR,t.created,ifnull(t.closed,now())) <= 24 then '3. Up to 24 Hours'\r\n            when TIMESTAMPDIFF( DAY,t.created,ifnull(t.closed,now())) <= 02 then '4. Up to 2 Days'\r\n            when TIMESTAMPDIFF( DAY,t.created,ifnull(t.closed,now())) <= 07 then '5. Up to 7 Days'\r\n            when TIMESTAMPDIFF( DAY,t.created,ifnull(t.closed,now()))  > 07 then '6. Greater than 8 Days'\r\n          end \"Creation Age\"\r\n      , count(*) Qty\r\n  from ost_ticket t\r\n where closed is null AND status_id IN (1,2,7)\r\n group by 1"
    }
   ]
  },
  {
   "title": "Open Tickets",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select count(*) Open\r\n  from ost_ticket \r\n where status_id IN(1,6,7) AND dept_id = 1"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 4 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) Opened\r\nFROM ost_ticket t\r\nWHERE cast(t.created AS date) = cast(NOW() AS date) AND dept_id = 1"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT sum(T.created >= date_format(subdate(now(),1), \"%Y-%m-%d\") AND T.created <= date_format(now(),\"%Y-%m-%d\"))\r\nFROM ost_ticket T\r\n\tJOIN ost_ticket_status S ON T.status_id = S.id\r\nWHERE T.dept_id = 1\r\n/*\r\nSELECT COUNT(*) Opened\r\nFROM ost_ticket t\r\nWHERE cast(t.created AS date) = cast(NOW() AS date) AND dept_id = 1*/"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 6 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) Closed\r\nFROM ost_ticket t\r\nWHERE cast(t.closed AS date) = cast(NOW() AS date) AND dept_id = 1"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 6 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT sum(T.closed >= date_format(subdate(now(),1), \"%Y-%m-%d\") AND T.closed <= date_format(now(),\"%Y-%m-%d\"))\r\nFROM ost_ticket T\r\n\tJOIN ost_ticket_status S ON T.status_id = S.id\r\nWHERE T.dept_id = 1\r\n/*\r\nSELECT COUNT(*) Closed\r\nFROM ost_ticket t\r\nWHERE cast(t.closed AS date) = cast(NOW() AS date) AND dept_id = 1*/"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) Reopened\r\nFROM ost_ticket t\r\nWHERE cast(t.reopened AS date) = cast(NOW() AS date) AND dept_id = 1"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT sum(T.reopened >= date_format(subdate(now(),1), \"%Y-%m-%d\") AND T.reopened <= date_format(now(),\"%Y-%m-%d\"))\r\nFROM ost_ticket T\r\n\tJOIN ost_ticket_status S ON T.status_id = S.id\r\nWHERE T.dept_id = 1\r\n/*\r\nSELECT COUNT(*) Reopened\r\nFROM ost_ticket t\r\nWHERE cast(t.reopened AS date) = cast(NOW() AS date) AND dept_id = 1*/"
    }
   ]
  },
  {
   "title": "Total Tickets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  CONCAT(DATE_FORMAT(created, \"%m-%d\"), \" - Opened\") AS metric,\n  $__timeGroupAlias(created,5m,0),\n  COUNT(ticket_id) AS value\nFROM ost_ticket\nWHERE\n  $__timeFilter(created)\n  AND dept_id = 1\nGROUP BY metric, time\nUNION\n  SELECT CONCAT(DATE_FORMAT(closed, \"%m-%d\"), \" - Closed\") AS metric,\n  $__timeGroupAlias(closed,5m,0),\n  COUNT(ticket_id) AS value\nFROM ost_ticket\nWHERE\n  $__timeFilter(closed)\n  AND dept_id = 1\nGROUP BY metric, time\nUNION\n  SELECT CONCAT(DATE_FORMAT(reopened, \"%m-%d\"), \" - Reopened\") AS metric,\n  $__timeGroupAlias(reopened,5m,0),\n  COUNT(ticket_id) AS value\nFROM ost_ticket\nWHERE\n  $__timeFilter(reopened)\n  AND dept_id = 1\nGROUP BY metric, time\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Open Ticket Trend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT CAST(t.date_time as date) time,\r\n      (SELECT COUNT(*) FROM ost_ticket\r\n        WHERE CAST(created AS date) <= t.date_time AND dept_id=1\r\n          AND ((status_id IN (1,6,7) AND closed IS NULL) OR CAST(closed AS date) > t.date_time)) Trend\r\n  FROM (SELECT CAST(created AS date) AS date_time, status_id FROM ost_ticket WHERE $__timeFilter(created) AND dept_id=1\r\n        UNION \r\n        SELECT CAST(closed AS date) AS date_time, status_id FROM ost_ticket WHERE $__timeFilter(closed) AND dept_id=1) t\r\n ORDER BY 1"
    }
   ]
  }
 ]
}